
#include <stdio.h>
#include <assert.h>

void micro() {
    long result = 0;
    asm volatile (
      "movq $0 , %%rax  \n\t"
      "movq $1,  %%rcx  \n\t"
      "movq $2,  %%rdx  \n\t"
      "movq $3,  %%rdi  \n\t"
      "movq $4,  %%rsi  \n\t"
      "movq $5,  %%r8   \n\t"
      "movq $6,  %%r9   \n\t"
      "movq $7,  %%r10  \n\t"
      "movq $8,  %%r11  \n\t"
      "movq $9,  %%r12  \n\t"
      "movq $10,  %%r13  \n\t"
      "movq $11,  %%r14  \n\t"
      "movq $12,  %%r15  \n\t"
      "movq $13,  %%r16  \n\t"
      "movq $14,  %%r17  \n\t"
      "movq $15,  %%r18  \n\t"
      "movq $16,  %%r19  \n\t"
      "movq $17,  %%r20  \n\t"
      "movq $18,  %%r21  \n\t"
      "movq $19,  %%r22  \n\t"
      "movq $20,  %%r23  \n\t"
      "movq $21,  %%r24  \n\t"
      "movq $22,  %%r25  \n\t"
      "movq $23,  %%r26  \n\t"
      "movq $24,  %%r27  \n\t"
      "movq $25,  %%r28  \n\t"
      "movq $26,  %%r29  \n\t"
      "movq $27,  %%r30  \n\t"
      "movq $28,  %%r31  \n\t"
      // Data being pushed by PUSH2 must be 16B-aligned on the stack, for this push rax upfront
      // and use it as a temporary register for stack alignment.
      "pushq %%rax       \n\t"
      // Move original stack pointer to RAX and align stack pointer to 16B boundary.
      "movq %%rsp, %%rax \n\t"
      "andq $-16 , %%rsp \n\t"
      // Push original stack pointer along with remaining registers on 16B aligned stack.
      // Note: For PPX to work properly, a PPX-marked PUSH2 (respectively, POP2) should always
      // be matched with a PPX-marked POP2 (PUSH2), not with two PPX-marked POPs (PUSHs).
      "push2p %%rcx, %%rax \n\t"
      "push2p %%rdi, %%rdx \n\t"
      "push2p %%r8, %%rsi  \n\t"
      "push2p %%r10, %%r9  \n\t"
      "push2p %%r12, %%r11  \n\t"
      "push2p %%r14, %%r13 \n\t"
      "push2p %%r16, %%r15  \n\t"
      "push2p %%r18, %%r17  \n\t"
      "push2p %%r20, %%r19 \n\t"
      "push2p %%r22, %%r21  \n\t"
      "push2p %%r24, %%r23  \n\t"
      "push2p %%r26, %%r25 \n\t"
      "push2p %%r28, %%r27  \n\t"
      "push2p %%r30, %%r29 \n\t"
      // To maintain 16 byte alignment after r11 is pushed.
      "subq $8,  %%rsp     \n\t"
      "pushp  %%r31  \n\t"

      // Re-set the GPRs
      "movq $-1 , %%rax  \n\t"
      "movq $-1,  %%rcx  \n\t"
      "movq $-1,  %%rdx  \n\t"
      "movq $-1,  %%rdi  \n\t"
      "movq $-1,  %%rsi  \n\t"
      "movq $-1,  %%r8   \n\t"
      "movq $-1,  %%r9   \n\t"
      "movq $-1,  %%r10  \n\t"
      "movq $-1,  %%r11  \n\t"
      "movq $-1,  %%r12  \n\t"
      "movq $-1,  %%r13  \n\t"
      "movq $-1,  %%r14  \n\t"
      "movq $-1,  %%r15  \n\t"
      "movq $-1,  %%r16  \n\t"
      "movq $-1,  %%r17  \n\t"
      "movq $-1,  %%r18  \n\t"
      "movq $-1,  %%r19  \n\t"
      "movq $-1,  %%r20  \n\t"
      "movq $-1,  %%r21  \n\t"
      "movq $-1,  %%r22  \n\t"
      "movq $-1,  %%r23  \n\t"
      "movq $-1,  %%r24  \n\t"
      "movq $-1,  %%r25  \n\t"
      "movq $-1,  %%r26  \n\t"
      "movq $-1,  %%r27  \n\t"
      "movq $-1,  %%r28  \n\t"
      "movq $-1,  %%r29  \n\t"
      "movq $-1,  %%r30  \n\t"
      "movq $-1,  %%r31  \n\t"
      // Restore stack.
      "popp   %%r31        \n\t"
      "addq   $8, %%rsp    \n\t"
      // Data being popped by pop2 must be 16B-aligned on the stack.
      "pop2p  %%r29,  %%r30 \n\t"
      "pop2p  %%r27,  %%r28 \n\t"
      "pop2p  %%r25,  %%r26 \n\t"
      "pop2p  %%r23,  %%r24 \n\t"
      "pop2p  %%r21,  %%r22 \n\t"
      "pop2p  %%r19,  %%r20 \n\t"
      "pop2p  %%r17,  %%r18 \n\t"
      "pop2p  %%r15,  %%r16 \n\t"
      "pop2p  %%r13,  %%r14 \n\t"
      "pop2p  %%r11,  %%r12 \n\t"
      "pop2p  %%r9,  %%r10 \n\t"
      "pop2p  %%rsi, %%r8  \n\t"
      "pop2p  %%rdx, %%rdi \n\t"
      "pop2p  %%rax, %%rcx \n\t"
      // Re-instantiate original stack pointer.
      "movq  %%rax,  %%rsp \n\t"
      "popq %%rax           \n\t"
      "cmpq $0 , %%rax    \n\t"
      "jne error          \n\t"
      "cmpq $1 , %%rcx    \n\t"
      "jne error          \n\t"
      "cmpq $2 , %%rdx    \n\t"
      "jne error          \n\t"
      "cmpq $3 , %%rdi    \n\t"
      "jne error          \n\t"
      "cmpq $4 , %%rsi    \n\t"
      "jne error          \n\t"
      "cmpq $5 , %%r8     \n\t"
      "jne error          \n\t"
      "cmpq $6 , %%r9     \n\t"
      "jne error          \n\t"
      "cmpq $7 , %%r10    \n\t"
      "jne error          \n\t"
      "cmpq $8 , %%r11    \n\t"
      "jne error          \n\t"
      "cmpq $9 , %%r12    \n\t"
      "jne error          \n\t"
      "cmpq $10 , %%r13    \n\t"
      "jne error          \n\t"
      "cmpq $11 , %%r14    \n\t"
      "jne error          \n\t"
      "cmpq $12 , %%r15    \n\t"
      "jne error          \n\t"
      "cmpq $13 , %%r16    \n\t"
      "jne error          \n\t"
      "cmpq $14 , %%r17    \n\t"
      "jne error          \n\t"
      "cmpq $15 , %%r18    \n\t"
      "jne error          \n\t"
      "cmpq $16 , %%r19    \n\t"
      "jne error          \n\t"
      "cmpq $17 , %%r20    \n\t"
      "jne error          \n\t"
      "cmpq $18 , %%r21    \n\t"
      "jne error          \n\t"
      "cmpq $19 , %%r22    \n\t"
      "jne error          \n\t"
      "cmpq $20 , %%r23    \n\t"
      "jne error          \n\t"
      "cmpq $21 , %%r24    \n\t"
      "jne error          \n\t"
      "cmpq $22 , %%r25    \n\t"
      "jne error          \n\t"
      "cmpq $23 , %%r26    \n\t"
      "jne error          \n\t"
      "cmpq $24 , %%r27    \n\t"
      "jne error          \n\t"
      "cmpq $25 , %%r28    \n\t"
      "jne error          \n\t"
      "cmpq $26 , %%r29    \n\t"
      "jne error          \n\t"
      "cmpq $27 , %%r30    \n\t"
      "jne error          \n\t"
      "cmpq $28 , %%r31    \n\t"
      "jne error          \n\t"
      "noerror:           \n\t"
      "movq $1,    %0     \n\t"
      "jmp done           \n\t"
      "error:             \n\t"
      "movq $-1,    %0    \n\t"
      "done:              \n\t"
      :  "=r"(result)
      :
      : "cc", "%rax", "%rcx", "%rdx", "%rdi", "%rsi", "%r8", "%r9", "%r10", "%r11", "r12", "r13", "r14", "r15", "r16", "r17", "r18"
    );
    assert(result == 1 && "incorrect result");
}

int main () {
  for (int i = 0; i < 1000000; i++) {
    micro();
  }
  return 0;
}
