/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jit */

#ifndef _Included_jit
#define _Included_jit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jit
 * Method:    eval
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jit_eval
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
