
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
 
#ifndef _Included_MICRO_NATIVE
#define _Included_MICRO_NATIVE

extern "C" {
/*
 */
JNIEXPORT jint JNICALL Java_jit_eval (JNIEnv *, jobject, jint a) {
  return a*10;
}
 
}

#endif
